---
- name: "check if golang {{ item.version }} already installed"
  ansible.builtin.command: "asdf list golang {{ item.version }}"
  register: version_installed
  no_log: yes
  ignore_errors: yes
  tags: [ langs ]

- name: "ensure golang {{ item.version }} plugin is installed"
  ansible.builtin.command: "asdf install golang {{ item.version }}"
  when: version_installed.rc > 0
  tags: [ langs ]
