---
- name: "check if sbt {{ item.version }} already installed"
  ansible.builtin.command: "asdf list sbt {{ item.version }}"
  register: version_installed
  no_log: yes
  ignore_errors: yes
  tags: [ langs ]

- name: "ensure sbt {{ item.version }} plugin is installed"
  ansible.builtin.command: "asdf install sbt {{ item.version }}"
  when: version_installed.rc > 0
  tags: [ langs ]
