---
- name: "check if nodejs {{ item.version }} already installed"
  ansible.builtin.command: "asdf list nodejs {{ item.version }}"
  register: version_installed
  no_log: yes
  ignore_errors: yes
  tags: [ langs ]

- name: "ensure nodejs {{ item.version }} plugin is installed"
  ansible.builtin.command: "asdf install nodejs {{ item.version }}"
  when: version_installed.rc > 0
  tags: [ langs ]

- name: "enable corepack yarn"
  ansible.builtin.command: "corepack enable"
  tags: [ langs ]

- name: "reshim nodejs"
  ansible.builtin.command: "asdf reshim nodejs"
  tags: [ langs ]
