---
- name: "check if {{ item.name }} already installed"
  ansible.builtin.command: "which {{ item.name }}"
  register: lang_installed
  tags: [ langs ]

- name: "ensure {{ item.name }} is install"
  homebrew:
    name: "{{ item.name }}"
    update_homebrew: yes
  when: lang_installed.rc > 0
  tags: [ langs ]
