---
# tasks to install doom emacs
- name: tap homebrew repositories
  homebrew_tap:
    name: "railwaycat/emacsmacport"
  tags: [ editors ]

- name: install emacs via homebrew
  homebrew_cask:
    name: "emacs-mac"
    update_homebrew: yes
  tags: [ editors ]

- name: install doom-emacs via git
  ansible.builtin.git:
    repo: https://github.com/doomemacs/doomemacs.git
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.emacs.d"
    depth: 1
  tags: [ editors ]

- name: install doom-emacs
  command: "{{ lookup('ansible.builtin.env', 'HOME') }}/.emacs.d/bin/doom install --force"
  register: std_output
  tags: [ editors ]

- name: print doom-emacs output
  debug:
    var: std_output.stdout
  tags: [ editors ]
