---
core:
  - xorg-server 
  - xorg-xinit 
  - compton
  - feh
sound:
  - sof-firmware
  - pipewire
  - pipewire-pulse
  - pipewire-alsa
  - alsa-utils
fonts:
  - ttf-dejavu
  - ttf-font-awesome
  - powerline
  - powerline-fonts
window:
  - i3-gaps
  - i3blocks
  - i3lock
  - i3status
  - dmenu
terminal:
  - alacritty
editor:
  - neovim
  - ripgrep
lang:
  - nodejs
  - npm
  - python
tools:
  - firefox
