---
- name: Set-up graphical server (xorg)
  hosts: localhost
  connection: local
  become: true
  vars:
    USER: smoate

  tasks:
  - name: alacritty
    include: playbooks/xorg.yml

- name: Set-up fonts
  hosts: localhost
  connection: local
  become: true
  vars:
    USER: smoate

  tasks:
  - name: fonts
    include: playbooks/fonts.yml

- name: Set up window manager (i3)
  hosts: localhost
  connection: local
  become: true
  vars:
    USER: smoate

  tasks:
  - name: i3
    include: playbooks/i3.yml

- name: Set-up terminal emulator (alacritty)
  hosts: localhost
  connection: local
  become: true
  vars:
    USER: smoate

  tasks:
  - name: alacritty
    include: playbooks/alacritty.yml
