---
- name: install zsh via homebrew
  homebrew:
    name: "zsh"
    update_homebrew: yes
  tags: [ term ]

- name: install oh-my-zsh # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.oh-my-zsh"
    depth: 1
  tags: [ term ]

- name: install zsh-autosuggestions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1
  tags: [ term ]

- name: install zsh-completions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-completions"
    depth: 1
  tags: [ term ]

- name: install zsh-syntax-highlighting plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-csyntax-highlighting"
    depth: 1
  tags: [ term ]

- name: ensure user shell -> zsh 
  become: true
  ansible.builtin.user:
    name: "{{ lookup('ansible.builtin.env', 'USER') }}"
    shell: /bin/zsh
  tags: [ term ]
