---
 - name: install xorg
   become: true
   package:
     name: '{{ core }}'
     state: present
   tags: gui


 - name: install sound
   become: true
   package:
     name: '{{ sound }}'
     state: present
   tags: gui


 - name: install fonts
   become: true
   package:
     name: '{{ fonts }}'
     state: present
   tags: gui


 - name: install window manager
   become: true
   package:
     name: '{{ window }}'
     state: present
   tags: gui


 - name: install terminal emulator
   become: true
   package:
     name: '{{ terminal }}'
     state: present
   tags: gui


 - name: install text editor
   become: true
   package:
     name: '{{ editor }}'
     state: present
   tags: gui


 - name: install languages
   become: true
   package:
     name: '{{ lang }}'
     state: present
   tags: gui


 - name: install tools
   become: true
   package:
     name: '{{ tools }}'
     state: present
   tags: gui


 - name: check if wallpapers exists
   stat:
     path: '/home/{{ user }}/wallpapers' 
   register: wallpaper


 - name: clone wallpapers
   git:
     repo: 'https://github.com/makccr/wallpapers'
     dest: '/home/{{ user }}/wallpapers' 
     depth: 1
     accept_hostkey: yes
   when: wallpaper.stat.exists == False

