---
- name: remove all applications from dock
  shell: "dockutil --remove all"
  when: dockitems_reset | bool
  changed_when: false
  tags: [ dock ]

- name: pause for 7 seconds between dock changes
  ansible.builtin.pause:
    seconds: 7
  tags: [ dock ]
