---
- name: reset .ssh dired
  ansible.builtin.include_tasks: ssh-reset.yml
  when: "{{ ssh_reset }}"
  tags: [ ssh ]

- name: ensure required ssh keys exist
  ansible.builtin.include_tasks: ssh-add.yml
  loop: "{{ ssh_persist }}"
  tags: [ ssh ]
