---
- name: reset .ssh dired
  ansible.builtin.include_tasks: ssh-reset.yml
  when: "{{ ssh_reset }}"
  tags: [ pre-install ]

- name: ensure required ssh keys exist
  ansible.builtin.include_tasks: ssh-add.yml
  loop: "{{ ssh_persist }}"
  tags: [ pre-install ]

- name: add keys to known_hosts
  ansible.builtin.include_tasks: ssh-known-hosts.yml
  when: "{{ ssh_reset }}"
  tags: [ pre-install ]

- name: set-url for bootstrap-script
  ansible.builtin.include_tasks: set-url-bootstrap.yml
  tags: [ pre-install ]

- name: set the hostname
  ansible.builtin.hostname:
    name: phoenix
  become: yes
  tags: [ pre-install ]
