---
 - name: update system
   become: true
   pacman:
     update_cache: true
     upgrade: true
   tags: core


 - name: install packages
   become: true
   package:
     name: '{{ common }}'
     state: present
   tags: core


 - name: check if .ssh exists
   stat:
     path: '/home/{{ user }}/.ssh'
   register: ssh_directory

 
 - name: ensure .ssh directory exists
   file:
     dest: '/home/{{ user }}/.ssh'
     mode: 0700
     owner: '{{ user }}'
     state: directory
   when: ssh_directory.stat.exists == False


 - name: install github private key
   copy:
     src: '{{ playbook_dir }}/files/github'
     dest: '/home/{{ user }}/.ssh/github' 
     mode: 0600
     owner: '{{ user }}'
     decrypt: true
   when: ssh_directory.stat.exists == False
   

 - name: install github public key
   copy:
     src: '{{ playbook_dir }}/files/github.pub'
     dest: '/home/{{ user }}/.ssh/github.pub' 
     mode: 0600
     owner: '{{ user }}'
   when: ssh_directory.stat.exists == False


 - name: start ssh-agent
   shell: 'eval $(ssh-agent -s) && ssh-add /home/{{ user }}/.ssh/github'
