---
# langauges to be installed by default
langs_persist: []
# asdf plugins to be installed by default
langs_asdf_plugins: []
# asdf python versions to be installed by default
langs_asdf_python: []
# asdf nodejs versions to be installed by default
langs_asdf_nodejs: []
