---
 - name: install zsh
   pacman:
     name: ['zsh']

 - name: change shell to zsh
   shell: "chsh -s $(which zsh) {{ USER }}"

 - name: check for oh-my-zsh
   stat:
     path: "/home/{{ USER }}/.oh-my-zsh"
   register: oh_my_zsh
 
 - name: download oh-my-zsh
   shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > "/home/{{ USER }}/.oh_my_installer"
   when: oh_my_zsh.stat.exists == False

 - name: make oh-my-zsh installer executable
   shell: chmod +x "/home/{{ USER }}/.oh_my_installer"
   when: oh_my_zsh.stat.exists == False

 - name: install oh-my-zsh
   shell: "/home/{{ USER }}/.oh_my_installer"
   when: oh_my_zsh.stat.exists == False
   become_user: "{{ USER }}"

 - name: remove oh-my-zsh installer
   shell: rm "/home/{{ USER }}/.oh_my_installer"
   when: oh_my_zsh.stat.exists == False
