---
 - name: register if .dotfiles exists
   stat:
     path: '{{ directory }}'
   register: dotfiles


 - name: clone .dotfiles
   git:
     repo: '{{ source }}'
     dest: '{{ directory }}'
     accept_hostkey: yes
   when: dotfiles.stat.exists == False


 - name: install .dotfiles
   shell: '{{ directory }}/install'
   when: dotfiles.stat.exists == False
