---
- name: "ensure {{ item.tap }} tapped"
  homebrew_tap:
    name: "{{ item.tap }}"
  tags: [ fonts ]

- name: "ensure {{ item.name }} installed"
  homebrew_cask:
    name: "{{ item.cask }}"
    update_homebrew: yes
  tags: [ fonts ]
